openapi: 3.0.3
info:
  title: Foyota Haven - Finance Stub
  description: Finance Stub API Documentation
  #   termsOfService: http://swagger.io/terms/
  #   contact:
  #     email: apiteam@swagger.io
  #   license:
  #     name: Apache 2.0
  #     url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
# externalDocs:
#   description: Find out more about Swagger
#   url: http://swagger.io
# servers:
#   - url: https://petstore3.swagger.io/api/v3
tags:
  - name: Gets
    description: Various GET requests for user information.
  - name: Buying
    description: Everything regarding buying products.
  - name: Loans
    description: Everything regarding loans.
  - name: Cleaning
    description: Additional functionality to clean up database (mainly for Pytests).
#     externalDocs:
#       description: Find out more about our store
#       url: http://swagger.io
#   - name: user
#     description: Operations about user
paths:
  /get/user/transactions:
    post:
      tags:
        - Gets
      summary: Returns a list of customer's transaction history
      description: Customer's Transaction History
      operationId: handle_get_user_transactions
      requestBody:
        description: Send in customer's email for their transaction history.
        content:
          application/json:
            schema:
              example: { "email": "customer@foyotahaven.com" }
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              example: { "email": "customer@foyotahaven.com" }

  /loanqualification:
    post:
      tags:
        - Financial Stub
      summary: Check Loan Qualification
      description: See if a customer qualifies for a loan.
      operationId: loanQualification
      requestBody:
        description: Send in customer's income, the car's price, and the customer's down payment to receieve the verdict.
        content:
          application/json:
            schema:
              example:
                {
                  "income": "50000",
                  "car_price": "50000",
                  "down_payment": "10000",
                }
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                example: { "approved": 0, "loan_approved": 40000.0 }

  /initialpayment:
    post:
      tags:
        - Financial Stub
      summary: Find initial monthly payment
      description: Finds initial monthly payment for a customer's loan.
      operationId: generateInitialPayment
      requestBody:
        description: Send in loan amount to receieve the monthly payment.
        content:
          application/json:
            schema:
              example: { "loan_amount": "5500" }
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                example: { "loan_amount": 5500.0, "monthly_payment": 91.67 }

  /payment:
    post:
      tags:
        - Financial Stub
      summary: Find subsequent monthly payments
      description: Finds subsequent monthly payment for a customer's loan.
      operationId: generatePayment
      requestBody:
        description: Send in loan amount, apr, created date, and last updated date to calculate and recieved the updated monthly payment.
        content:
          application/json:
            schema:
              example:
                {
                  "loan_amount": "5408.33",
                  "apr": 12.0,
                  "created": "2024-03-31 00:59:43",
                  "last_updated": "2024-04-30 00:59:43",
                }
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                example: { "loan_amount": 5462.41, "monthly_payment": 92.58 }
  /validatebankpayment:
    post:
      tags:
        - Financial Stub
      summary: Checks if Bank Payment is valid
      description: Performs many checks to see if the bank payment is valid.
      operationId: validateBankPayment
      requestBody:
        description: Send in bank, accounting number, and routing number to see if it is valid.
        content:
          application/json:
            schema:
              example:
                {
                  "bank": "Bank of America",
                  "account_number": "123123123123",
                  "routing_number": "021200339",
                }
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                example: { "loan_amount": 5500.0, "monthly_payment": 91.67 }
  /validatecardpayment:
    post:
      tags:
        - Financial Stub
      summary: Checks if Card Payment is valid
      description: Performs many checks to see if the card payment is valid.
      operationId: validateCardPayment
      requestBody:
        description: Send in card company, card number, card expiration date, and card cvc code to see if it is valid.
        content:
          application/json:
            schema:
              example:
                {
                  "card_company": "Visa",
                  "card_num": "4490 4978 3645 2232",
                  "card_exp": "10/2024",
                  "card_cvc": "173",
                }
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                example:
                  {
                    "errorType": 0,
                    "isValid": 1,
                    "message": "Card Payment Details Verified!",
                  }
